### PR TITLE
Fixes, removed loader and change text for Pull request button

### PR DESCRIPTION
**Pull request by carlosfrontend**
Fixes, removed loader and change text for Pull request button

### CODE REVIEW

**Comment by carlosfrontend** [comment]
Hello @MattCrl , I have solved the problems and added some new features. Could it be merged?. Tahnks!

**Comment by carlosfrontend** [comment]
I finished it now ...

**Comment by MattCrl** [comment]
Hey ! Sorry got some health troubles these last days, can't check PRs like last weeks. I merge this one , nice job :)

**Comment by carlosfrontend** [comment]
Thank you for merging it, I am also with health problems this week. I hope you get better soon.

**Pull request merged**
