### PR TITLE
Added my profile card

### PR DESCRIPTION
**Pull request by mateohoxha**
I added my profile bootstrap v4 card with my profile image and some informations.

### CODE REVIEW

**Comment by MattCrl** [comment]
Well you actually removed my card with yours lol, please change it ;). 
CSS changes is original ^^

**Comment by mateohoxha** [comment]
I added your personal card !

**Comment by MattCrl** [comment]
Master has changed alot since your first PR , please merge actual master with your branch and solve conflicts , thanks :)

**Comment by MattCrl** [comment]
You forgot to remove some code like Doctype, head, etc... I let you remove it before merging

**Pull request closed without merging**
