### PR TITLE
Added my card and CSS to all cards (did the requested changes)

### PR DESCRIPTION
**Pull request by dushivani**

### CODE REVIEW

**Comment by MattCrl** [comment]
Hi, don't need to give a dimension to images, CSS isn't okay actually, no more margin bottom between cards, better leave the CSS like it was before for images (text center is fine)

**Comment by dushivani** [comment]
Done.

**Comment by MattCrl** [comment]
I can't merge it, some things are broken. Cards aren't same height (they are on actual master version), and there's a div that is not closed

**Comment by MattCrl** [comment]
Closing this PR for the moment, feel free to open a new one when changes are done ;)

**Pull request closed without merging**
