### PR TITLE
Added Countdown in main page and buttons for Official WebPage and Git…

### PR DESCRIPTION
**Pull request by carlosfrontend**
…Hub Page

### CODE REVIEW

**Comment by MattCrl** [comment]
Nice ! Can you remove the alert of the countdown now that it's on the main page please ? And fix a bit CSS indentation , then i'll merge it :)

**Comment by carlosfrontend** [comment]
I'm removing modal now :+1:

**Comment by carlosfrontend** [comment]
Can you check it now? Thanks...

**Comment by MattCrl** [comment]
Can't right now i'm at work, but i'll check it tonight at home if I have time :) I hope so. Thanks for everything you do for this project !

**Comment by MattCrl** [comment]
I merged it but there will be a little fix for the button "Submit youR* pull request" , and is it possible to remove the "Loading" that is displayed when we visit the website ? Would be great :)

**Comment by carlosfrontend** [comment]
I'm removing now loader. What you mean whith submit your pull request button ? Change only the text of button?

**Comment by MattCrl** [comment]
Yes the "R" was missing from "youR"

**Comment by carlosfrontend** [comment]
I did a new pull request...

**Pull request merged**
